name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: sudo apt-get install libboost-system-dev libboost-filesystem-dev libexpat1-dev 
    - name: configure
      run: mkdir build && cd build && cmake ../
    - name: make
      run: cd build && cmake --build .

